
# \u5BA2\u6237\u7AEF\u6CE8\u518C\u7684\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#  instance:
#    hostname: clientName #\u81EA\u5B9A\u4E49\u70B9\u51FB\u94FE\u63A5\u8DF3\u8F6C\u7684\u5730\u5740\u540D\u79F0
# \u81EA\u5B9A\u4E49\u5BA2\u6237\u7AEF\u540D\u79F0
spring:
  application:
    name: client
server:
  port: 8771
