
# \u5BA2\u6237\u7AEF\u6CE8\u518C\u7684\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

#  instance:
#    hostname: clientName #指定由eureka中statu点击跳转的url
# \u81EA\u5B9A\u4E49\u5BA2\u6237\u7AEF\u540D\u79F0
spring:
  application:
    name: employee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql:///cls?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#server:
#  port: 8771

# mapper.xml文件地址
mybatis:
  mapperLocations: classpath:com.alimama.server.mapper/*.xml
